# For more info on HTTP files go to https://aka.ms/vs/httpfile
//GetAll
send Request
GET http://localhost:5167/todos

###
//GetById
send Request
GET http://localhost:5167/todos/3

###

send Request
POST http://localhost:5167/todos
content-type: application/json 


{
    "id": 1,
    "name": "Write Demo 1",
    "DueDate": "2024-11-10",
    "isCompleted": false
}

###
//DeleteById
send Request
DELETE http://localhost:5167/todos/2
###

send Request
DELETE http://localhost:5167/todos
###

GET http://localhost:5167/tasks/1 

###


